Modules/Netex/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/admin/netex')->middleware(['auth'])->name('admin.')->group(function() {
    Route::view('/','netex::import')->name('netex.index');
    Route::post('/import', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'import'])->name('netex.import');
    Route::post('/import/log', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'saveImportNetexSuccess'])->name('netex.import.log');
    Route::get('/import/log', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'viewLogImportNetexSuccess'])->name('netex.import.log');
    Route::post('/import/log/detail', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_ild'])->name('netex.import.log.detail');
    Route::get('/line', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'line'])->name('netex.line');
    Route::post('/processline', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_line'])->name('netex.processline');
    Route::get('/route', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'route'])->name('netex.route');
    Route::post('/processroute', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_route'])->name('netex.processroute');
    Route::get('/servicejourney', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'service_journey'])->name('netex.servicejourney');
    Route::post('/processsj', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_sj'])->name('netex.processsj');
    Route::get('/destinationdisplay', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'destination_display'])->name('netex.destinationdisplay');
    Route::post('/processdd', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_dd'])->name('netex.processdd');
    Route::get('/journeylayover', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'journey_layover'])->name('netex.journeylayover');
    Route::post('/processjl', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_jl'])->name('netex.processjl');
    Route::get('/stoparea', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'stop_area'])->name('netex.stoparea');
    Route::post('/processsa', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_sa'])->name('netex.processsa');

    Route::get('/scheduledstoppoint', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'scheduled_stop_point'])->name('netex.scheduledstoppoint');
    Route::post('/process_ssp', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_ssp'])->name('netex.process_ssp');

    Route::get('/route/line', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'route_line'])->name('netex.routeline');
    Route::post('/processrl', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_rl'])->name('netex.processrl');
    Route::get('/journeyplanner', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'journeyplanner'])->name('netex.journeyplanner.index');
    Route::post('/processsp', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'process_sp'])->name('netex.processsp');
    Route::get('/route/line/view', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'routeline_view'])->name('netex.routeline.view');
    Route::get('/route/line/detail', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'routeline_detail'])->name('netex.routeline.detail');
    Route::get('/journeyplanner/detail', [Modules\Netex\Http\Controllers\Backend\NetexController::class, 'journeyplannerdetail'])->name('netex.journeyplanner.detail');
});

Modules/Netex/Resources/views/journeyplanner/detail.blade.php
@extends('theme::views.backend.app')

@section('page-title')
<h2>Journey Planner Time Table</h2>
@endsection

@section('breadcrumb')
<ol class="breadcrumbs">
	<li>
		<a href="index.html">
			<i class="fa fa-home"></i>
		</a>
	</li>
	<li><span>Journey Planner Time Table</span></li>
</ol>
@endsection

@section('content')

@push('data-stylesheets-custom')
<link rel="stylesheet" href="{{ Module::asset('netex:sass/stockpoint.min.css') }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
@endpush

<div class="row">
	<div class="col-md-12 col-lg-12">
		<button class="prevtab btn btn-primary" style="height: 100px;float: left;max-width: 50px;"><i class="fa fa-arrow-circle-left"></i></button>		
		<ul class="nav nav-tabs" id="div1" style="border: none;display: flex;overflow-x: auto;overflow-y: hidden;float: left;width: 1200px;">
			@php $no = 1; $nomor = 0; $starttime = 0; $endtime = 0; $switch = 1; $tempstarttime = 0; $diff = 0; $sum = 0; $nextruntimebef = 0; $waittimestopbef = 0; @endphp
			@foreach($result as $row)
			@if($row->orders=='1.00')
			@php $switch = 2; $sum = 0; @endphp
			@endif
			@if($row->orders=='1.00')
			@php 
			$starttime = strtotime($row->departure_time) + $row->stop_wait_time;
			$nextruntimebef = $row->next_run_time;
			$waittimestopbef = $row->stop_wait_time;
			@endphp
			@else
			@php 
			$sum = $sum + $row->stop_wait_time + $nextruntimebef + $waittimestopbef;
			$nextruntimebef = $row->next_run_time;
			$waittimestopbef = $row->stop_wait_time;
			@endphp		
			@endif
			@if($no != 1 && $switch==2)
			@php 
			$nomor++; 
			@endphp
			<li class="nav-link @if($nomor==1) active @endif">
				<a href="#popular{{ $nomor }}" data-toggle="tab" aria-expanded="true">
					<div class="font-weight-bold m-0 text-left">
						<span class="journey-option__time-option">{{ gmdate("H:i:s", $tempstarttime) }}</span>
						<i class="fas fa-arrow-right"></i> <br>
						<span class="journey-option__time-option">{{ gmdate("H:i:s", $endtime) }}</span>
					</div>
					<div class="m-t-5 text-left">
						<span title="Overstappen"><i class="far icon-overstappen"></i> 0</span> | <span title="Reistijd"><i class="far icon-clock"></i>   <span>{{ gmdate("H:i:s", $diff) }}</span>
					</span>
				</div>
			</a>
		</li>
		@else
		@php 
		$tempstarttime = $starttime;
		$endtime = strtotime($row->departure_time) + $sum;
		if($endtime > $starttime){
			$diff = $endtime - $starttime;
		}else{
			$diff = $starttime - $endtime;
		}
		@endphp
		@endif
		@php $no++; $switch = 1; @endphp
		@endforeach
	</ul>	
	<button class="nexttab btn btn-primary" style="height: 100px;float: left;margin-left: 2px;max-width: 50px;"><i class="fa fa-arrow-circle-right"></i></button>	
</div>
</div>

<div class="row">
	<div class="col-md-12 col-lg-12">
		
		<div class="timeline">
			<div class="tm-body">
				<div class="tab-content" style="background-color: transparent;box-shadow: none;">
					@php $no = 1; $nomor = 0; $noarray = 1; $starttime = 0; $endtime = 0; $switch = 1; $tempstarttime = 0; $diff = 0; $arraytemp = []; $array = []; $sum = 0; $nextruntimebef = 0; $waittimestopbef = 0; @endphp
					@foreach($result as $row)
					@if($row->orders=='1.00')
					@php $switch = 2; $array = []; $noarray = 1; $sum = 0; @endphp
					@endif
					@php 
					if($row->orders=='1.00'){
						$sum = $sum  + $row->stop_wait_time;
						$nextruntimebef = $row->next_run_time;
						$waittimestopbef = $row->stop_wait_time;
					}else{
						$sum = $sum + $row->stop_wait_time + $nextruntimebef + $waittimestopbef;
						$nextruntimebef = $row->next_run_time;
						$waittimestopbef = $row->stop_wait_time;
					}
					$array[$noarray]['name'] = $row->stop_name;
					$array[$noarray]['time'] = strtotime($row->departure_time) + $sum;
					@endphp
					@if($no != 1 && $switch==2)
					@php 
					$nomor++;
					@endphp
					<div id="popular{{ $nomor }}" class="tab-pane @if($nomor==1) active @endif">
						<ol class="tm-items">
							@for ($i = 1; $i <= count($arraytemp); $i++)
							<li>
								<div class="tm-info">
									<div class="tm-icon"><i class="fa fa-map-marker"></i></div>
									<time class="tm-datetime" datetime="2013-11-22 19:13">
										<div class="tm-datetime-date">Departure Time</div>
										<div class="tm-datetime-time">{{ gmdate("H:i:s", $arraytemp[$i]['time']) }}</div>
									</time>
								</div>
								<div class="tm-box appear-animation" data-appear-animation="fadeInRight"data-appear-animation-delay="100">
									<p>
										<i class="fa fa-star" style="font-size: 15px;"></i>		{{ $arraytemp[$i]['name'] }}
									</p>
									<div class="well info" style="padding-bottom: 2px !important;padding-top: 8px !important;margin-bottom: 0px;">
										<b>Arrival Time</b>
										<div class="well primary" style="padding: 5px !important;">
											<i class="fa fa-map-marker"></i> {{ gmdate("H:i:s", $arraytemp[$i]['time'] - $row->stop_wait_time) }}
										</div>
									</div>
								</div>
							</li>
							@endfor
						</ol>
					</div>
					@php $arraytemp = []; @endphp
					@else
					@for ($i = 1; $i <= count($array); $i++)
					@php 
					$arraytemp[$i]['name'] = $array[$i]['name'];
					$arraytemp[$i]['time'] = $array[$i]['time'];
					@endphp
					@endfor
					@endif
					@php $no++; $noarray++; $switch = 1; @endphp
					@endforeach
				</div>
			</div>
		</div>
	</div>
</div>
@push('data-table')
<script src="{{ Module::asset('netex:assets/vendor/jquery-appear/jquery.appear.js') }}"></script>
@endpush
@push('data-scripts')
<script src="{{ Module::asset('netex:compiled/stockpoint.min.js') }}"></script>
@endpush
@push('core-scripts')
<script src="{{ $urltheme }}/backend/js/core.js"></script>
@endpush

@endsection

Modules/Netex/Resources/views/journeyplanner/index.blade.php
@extends('theme::views.backend.app')

@section('page-title')
<h2>Journey Planner Time Table</h2>
@endsection

@section('breadcrumb')
<ol class="breadcrumbs">
	<li>
		<a href="index.html">
			<i class="fa fa-home"></i>
		</a>
	</li>
	<li><span>Journey Planner Time Table</span></li>
</ol>
@endsection

@section('module_css')
    <link rel="stylesheet" href="/assets/Netex/css/journeyplanner.min.css" />
@endsection

@section('content')

{{-- @push('data-stylesheets')
<link rel="stylesheet" href="{{ Module::asset('netex:css/bootstrap-datetimepicker.css') }}" media="screen">
<link rel="stylesheet" href="{{ Module::asset('netex:assets/vendor/bootstrap-datepicker/css/datepicker3.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('netex:assets/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('netex:assets/vendor/select2/select2.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('netex:assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css') }}" />
@endpush --}}
<style type="text/css">
	.load-bgImage-Point {
		background: url("/themes/maestronic/assets/backend/assets/vendor/jstree/themes/default/throbber.gif") 270px 6px no-repeat !important;
	}
</style>
<div class="row">
	<div class="col-md-4 col-lg-4">
		<section class="panel">
			<header class="panel-heading">
				<div class="panel-actions">
					<a href="#" class="fa fa-caret-down"></a>
					<a href="#" class="fa fa-times"></a>
				</div>
				<h2 class="panel-title">Journey Planner Time Table</h2>
			</header>
			<input type="hidden" name="urlinfo" data-url="{{ route('admin.netex.processsp') }}">
			<div class="panel-body">
				<div class="tabs">
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#popular" data-toggle="tab" aria-expanded="true">Planner</a>
						</li>
						<li class="">
							<a href="#recent" data-toggle="tab" aria-expanded="false">Extra Opties</a>
						</li>
					</ul>
					<style type="text/css">
						.select2-arrow {
							display: none !important;
						}
					</style>
					<div class="tab-content">
						<div id="popular" class="tab-pane active">
							<form action="{{ route('admin.netex.journeyplanner.detail') }}" type="GET">
								<div class="timeline timeline-simple mt-xlg mb-md">
									<div class="tm-body">
										<div class="tm-title">
											<h3 class="h5 text-uppercase">Location</h3>
										</div>
										<ol class="tm-items">
											<li>
												<div class="tm-box">
													<div class="row">
														<div class="col-sm-12">
															<div class="form-group">
																<select data-plugin-selectTwo class="form-control populate selectClass1" id="locationStart">
																</select>
															</div>
														</div>
													</div>
													<div class="toggle" data-plugin-toggle="">
														<section class="toggle">
															<label>Voeg 'via' toe</label>
															<div class="toggle-content" style="display: none;">
																<div class="row">
																	<div class="col-sm-12">
																		<div class="form-group">
																			<select data-plugin-selectTwo class="form-control populate selectClass2"  id="locationCenter">
																			</select>
																		</div>
																	</div>
																</div>
															</div>
														</section>
													</div>
												</div>
											</li>
											<li>
												<div class="tm-box">
													<div class="row">
														<div class="col-sm-12">
															<div class="form-group">
																<select data-plugin-selectTwo class="form-control populate selectClass3" id="locationEnd">
																</select>
															</div>
														</div>
													</div>
												</div>
											</li>
										</ol>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-8">
										<div class="form-group">
											<label class="control-label">Date</label>
											<div class="input-group">
												<span class="input-group-addon">
													<i class="fa fa-calendar"></i>
												</span>
												<input type="text" data-plugin-datepicker class="form-control" name="dates">
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="form-group">
											<label class="control-label">Time</label>
											<div class="input-group">
												<span class="input-group-addon">
													<i class="fa fa-clock-o"></i>
												</span>
												<input type="text" name="times" data-plugin-timepicker class="form-control" data-plugin-options='{ "showMeridian": false }'>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-8">
										<div class="form-group">
											<label class="control-label">Type reis</label>
											<div class="row">
												<div class="col-sm-6">
													<div class="radio-custom radio-primary">
														<input type="radio" id="radioExample1" name="reis" checked>
														<label for="radioExample1">Vertrek</label>
													</div>
												</div>
												<div class="col-sm-6">
													<div class="radio-custom radio-primary">
														<input type="radio" id="radioExample2" name="reis">
														<label for="radioExample2">Aankomst</label>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<div class="form-group">
											<button type="submit" class="mb-xs mt-xs mr-xs btn btn-primary btn-block">Plan mijn reis</button>
										</div>
									</div>
								</div>
							</form>
						</div>
						<div id="recent" class="tab-pane">
							<div class="row">
								<div class="col-sm-8">
									<div class="form-group">
										<label class="control-label">Extra Opties</label>
										<div class="row">
											<div class="col-sm-6">
												<div class="radio-custom radio-primary">
													<input type="radio" id="radioExample1" name="radioExample" checked>
													<label for="radioExample1">Standaard</label>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="radio-custom radio-primary">
													<input type="radio" id="radioExample2" name="radioExample">
													<label for="radioExample2">+5 min.</label>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-8">
									<div class="form-group">
										<label class="control-label">Vervoermiddelen</label>
										<div class="row">
											<div class="col-sm-2">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample1" name="checkboxExample" checked>
													<label for="checkboxExample1"><i class="fa fa-bus"></i></label>
												</div>
											</div>
											<div class="col-sm-2">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample2" name="checkboxExample" checked>
													<label for="checkboxExample2"><i class="fa fa-train"></i></label>
												</div>
											</div>
											<div class="col-sm-2">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample2" name="checkboxExample" checked>
													<label for="checkboxExample2"><i class="fa fa-subway"></i></label>
												</div>
											</div>
											<div class="col-sm-2">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample2" name="checkboxExample" checked>
													<label for="checkboxExample2"><i class="fa fa-subway"></i></label>
												</div>
											</div>
											<div class="col-sm-2">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample2" name="checkboxExample" checked>
													<label for="checkboxExample2"><i class="fa fa-ship"></i></label>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-8">
									<div class="form-group">
										<label class="control-label">Toegankelijk plannen</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="checkbox-custom checkbox-primary">
													<input type="checkbox" id="checkboxExample1" name="checkboxExample">
													<label for="checkboxExample1"><i class="fa  fa-question-circle"></i></label>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<a href="{{ route('admin.netex.journeyplanner.detail') }}" class="mb-xs mt-xs mr-xs btn btn-primary btn-block">Plan mijn reis</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>	
			</div>
		</section>	
	</div>
</div>
{{-- @push('data-table')
<script src="{{ Module::asset('netex:assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
<script src="{{ Module::asset('netex:assets/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js') }}"></script>
<script src="{{ Module::asset('netex:assets/vendor/select2/select2.js') }}"></script>
<script src="{{ Module::asset('netex:assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js') }}"></script>
@endpush
@push('data-scripts')
<script src="{{ Module::asset('netex:js/stockpoint.js') }}"></script>
@endpush --}}

@endsection

@section('module_javascript')
<script src="/assets/Core/js/core.min.js"></script>
<script src="/assets/Netex/js/journeyplanner.min.js"></script>
@endsection