Modules/Gtfs/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['prefix'=>'/u/gtfs','middleware' => ['auth','tenancy.enforce']],function (){
Route::prefix('/admin/gtfs')->middleware(['auth'])->name('admin.')->group(function() {
    Route::get('/agency', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'agency'])->name('gtfs.agency');
    Route::post('/processagency', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_agency'])->name('gtfs.process.agency');
    Route::get('/calendar/dates', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'calendar_date'])->name('gtfs.calendar.dates');
    Route::post('/processcalendardates', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_calendardates'])->name('gtfs.process.calendar.dates');
    Route::get('/feed/info', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'feed_info'])->name('gtfs.feed.info');
    Route::post('/processfeedinfo', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_feedinfo'])->name('gtfs.process.feed.info');
    Route::get('/routes', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'routes'])->name('gtfs.routes');
    Route::post('/processroutes', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_routes'])->name('gtfs.process.routes');
    Route::get('/shapes', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'shapes'])->name('gtfs.shapes');
    Route::post('/processshapes', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_shapes'])->name('gtfs.process.shapes');
    Route::get('/stop/times', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'stop_times'])->name('gtfs.stop.times');
    Route::post('/processstoptimes', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_stoptimes'])->name('gtfs.process.stop.times');
    Route::get('/stops', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'stops'])->name('gtfs.stops');
    Route::post('/processstops', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_stops'])->name('gtfs.process.stops');
    Route::get('/transfers', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'transfers'])->name('gtfs.transfers');
    Route::post('/processtransfers', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_transfers'])->name('gtfs.process.transfers');
    Route::get('/trips', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'trips'])->name('gtfs.trips');
    Route::post('/processtrips', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'process_trips'])->name('gtfs.process.trips');
    Route::get('/import/show', [Modules\Gtfs\Http\Controllers\Backend\GtfsController::class, 'import'])->name('gtfs.import.show');

    //Import Log
    Route::post('/import/log', [Modules\Gtfs\Http\Controllers\Backend\ImportLogController::class, 'saveImportSuccess'])->name('gtfs.import.log.save');
    Route::get('/import/log', [Modules\Gtfs\Http\Controllers\Backend\ImportLogController::class, 'viewLogImportSuccess'])->name('gtfs.import.log.view');
    Route::post('/import/log/detail', [Modules\Gtfs\Http\Controllers\Backend\ImportLogController::class, 'process_ild'])->name('gtfs.import.log.detail');
});

Modules/Gtfs/Resources/views/trips/index.blade.php
@extends('theme::views.backend.app')

@section('page-title')
<h2>GTFS</h2>
@endsection

@section('breadcrumb')
<ol class="breadcrumbs">
	<li>
		<a href="index.html">
			<i class="fa fa-home"></i>
		</a>
	</li>
	<li><span>GTFS</span></li>
</ol>
@endsection

@section('module_css')
    <link rel="stylesheet" href="/assets/Gtfs/css/trips.min.css" media="screen" />
@endsection

@section('content')
{{-- 
@push('data-stylesheets')
<link rel="stylesheet" href="{{ Module::asset('gtfs:assets/vendor/select2/select2.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('gtfs:assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('gtfs:assets/vendor/jquery-datatables-bs3/assets/css/datatables.css') }}" />
<link rel="stylesheet" href="{{ Module::asset('gtfs:datatable/buttons.dataTables.min.css') }}" >
@endpush --}}

<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="row">
			<div class="col-md-12 col-lg-12 col-xl-12">
				<section class="panel">
					<header class="panel-heading">
						<div class="panel-actions">
							<a href="#" class="fa fa-caret-down"></a>
							<a href="#" class="fa fa-times"></a>
						</div>
						<h2 class="panel-title">Trips</h2>
					</header>
					<input type="hidden" name="urlinfo" data-url="{{ route('admin.gtfs.process.trips') }}">
					<div class="panel-body">
						<table class="table table-bordered table-striped mb-none" id="dataTableRowTrips">
							<thead>
								<tr>
									<th>Trip ID</th>
									<th>Route ID</th>
									<th>Service ID</th>
									<th>Realtime Trip ID</th>
									<th>Trip Headsign</th>
									<th>Trip Short Name</th>
									<th>Trip Long Name</th>
									<th>Direction ID</th>
									<th>Block ID</th>
									<th>Shape ID</th>
									<th>Wheelchair Accessible</th>
									<th>Bikes Allowed</th>
								</tr>
							</thead>
						</table>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
{{-- @push('data-table')
<script src="{{ Module::asset('gtfs:assets/vendor/select2/select2.js') }}"></script>
<script src="{{ Module::asset('gtfs:assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js') }}"></script>
<script src="{{ Module::asset('gtfs:datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ Module::asset('gtfs:datatable/buttons.html5.min.js') }}"></script>
<script src="{{ Module::asset('gtfs:datatable/dataTables.buttons.min.js') }}"></script>
<script src="{{ Module::asset('gtfs:assets/vendor/jquery-datatables-bs3/assets/js/datatables.js') }}"></script>
@endpush
@push('data-scripts')
<script src="{{ Module::asset('gtfs:compiled/trips.min.js') }}"></script>
@endpush --}}

@endsection

@section('module_javascript')
<script src="/assets/Core/js/core.min.js"></script>
<script src="/assets/Gtfs/js/trips.min.js"></script>
@endsection